### PR TITLE
Removed workaround in test.

### PR DESCRIPTION
**Pull request by oskarwrobel**
Missing cleanup after https://github.com/ckeditor/ckeditor5-engine/issues/455.

### CODE REVIEW

**Comment by pomek** [comment]
Everything works correctly but I'm not sure whether [your branch was named properly](https://github.com/ckeditor/ckeditor5/issues/246).

**Comment by oskarwrobel** [comment]
Why?

`In other repositories you create only PRs but clearly referencing the original PR (branch names t/ckeditor5-trigger-repo/xxx).`

**Comment by pomek** [comment]
Did you read the comments and a [summary](https://github.com/ckeditor/ckeditor5/issues/246#issuecomment-234288486)?

**Comment by oskarwrobel** [comment]
Alright thanks! I didn't know about this rule.

**Pull request merged**
