### PR TITLE
Introduced the superscript and the subscript features

### LINKED ISSUE #76: Create basic implementation of sub/sup features
In contrast to the https://github.com/ckeditor/ckeditor5-basic-styles/issues/75, which defines its advanced usage, edge cases, and semantics, this issue should be used as a base requirement for the https://github.com/ckeditor/ckeditor5-basic-styles/pull/74.

The sub/sup features should:
* working in base scenarios
* do not crash the editor
* have their own buttons, which look can be improved in the future
* have a manual sample

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Introduced the `Superscript` and the `Subscript` features. Closes #76. Closes #74.

---

### Additional information

This PR is a clone of the https://github.com/ckeditor/ckeditor5-basic-styles/pull/74 (good job @idleb), so we could add commit to it (@oleq has changed the icons), which was impossible on the original PR's branch.

### CODE REVIEW

**Comment by oleq** [comment]
Don't forget to add the icons to the iconset manual test in `ckeditor5-theme-lark`.

**Comment by ma2ciek** [comment]
> Missing updates in the docs/features/basic-styles.md.

Fixed.

**Comment by Reinmar** [comment]
image

Ekhm :P

I'll add them there.

**Comment by Reinmar** [comment]
I was about to merge and then:

image

Always test.

BTW, can you spot what's wrong here?

image

**Pull request merged**
