### PR TITLE
Hidden the button labels

### LINKED ISSUE #3: Hide the button label
It's a quick fix (actually, a hack) to have a compact UI in the very first milestone. 

The general toolbar configuration topic will be continued in https://github.com/ckeditor/ckeditor5-design/issues/143.

### PR DESCRIPTION
**Pull request by oleq**
Closes #3.

### CODE REVIEW

**Comment by Reinmar** [comment]
Don't you feel that the option should actually be called `withText`?

**Comment by oleq** [comment]
Maybe. A good point. It depends which will be the most common use–case: button with text or just an icon?

**Comment by Reinmar** [comment]
Looking at all existing solutions, without text. I'll create a ticket for that.

**Comment by Reinmar** [comment]
Done: https://github.com/ckeditor/ckeditor5-ui-default/issues/30

**Pull request merged**
