### PR TITLE
Add subscript and superscript feature

### PR DESCRIPTION
**Pull request by idleb**
I noticed that basic-styles look as if coreStyles in CKEditor4, but I didn't find subscript and superscript features, so I added them like CKEditor4

### CODE REVIEW

**Comment by ma2ciek** [comment]
Hi @idleb!

Thanks for the PR.

Could you tell us:

- What are your use cases for this feature? 
- Why do you think this feature is important?

We usually start by creating issues, so we can deeply discuss use cases for every feature and code change in our codebase. Note, that CKE4 and CKE5 are different editors, they have a little bit different usage and their features don't match 1-1.

In the past, we considered `<sub>` and `<sup>` elements being not necessary (see https://github.com/ckeditor/editor-recommendations/issues/5). But I see that the W3C recommendations for this script might have changed as the links in the above ticket are inactive. Now there's only a link to both features ( https://www.w3.org/TR/html5/textlevel-semantics.html#the-sub-and-sup-elements) with the following information: 
> In general, authors should use these elements only if the absence of those elements would change the meaning of the content.

**Comment by idleb** [comment]
Hi @ma2ciek ,I just saw that about `<sub>` and `<sup>` issues.

First, I am migrating from CKEditor4, and latest editor used this features for mathematical equation. because our product usually was used by teachers in school, e.g. print test paper. So we need these styles.

I think use `sub` and `sup` is more easily, but you are right about it's not a general function. Maybe,  I should implement them in a new package.

**Comment by Reinmar** [comment]
I don't see it a problem that Editor Recommendations don't consider sub/sup as semantic enough. ER didn't mean to define the set of features that we can never exceed. It was meant to define a basic set of "Article" oriented features. We already extended that set because there are other use cases than creating articles in CKEditor 5.

BTW, even in this package we have underline and code (and they are not covered by ER). We can easily have sub/sup too.

So, I'd really like to see a progress with sub/sup. @idleb, if you could reopen the PR, that'd be cool. It adds a very basic sub/sup functionality and that's ok for now.

But, I agree with @ma2ciek on one thing – we need to discuss how this feature should be provided. There are things like... can text be in `<sub>` and `<sup>` at the same time? If yes, which of these elements comes first (which one is outside)? How to implement it to achieve such behaviour (I can tell that it won't be that easy if these attrs are to be ordered)?

**Comment by idleb** [comment]
@Reinmar ,I am glad you asked me to reopen the PR, this feature is very basic. I don't consider about text is in <sub> and <sup> at the same time, which one is outside depend on how user typesetting.

**Comment by Reinmar** [comment]
OK, I reported the ticket about the behaviour of this feature: https://github.com/ckeditor/ckeditor5-basic-styles/issues/75

**Comment by ma2ciek** [comment]
Hi again, @idleb.

Sorry for the late review. 

I've tested it and it works fine, good job 👍. With the current implementation, you can have both `subscript` and `superscript`, but for now, it's ok.

Two things are missing now:
* updated `contexts.json` file (https://github.com/ckeditor/ckeditor5-basic-styles/blob/master/lang/contexts.json) with label translations
* updated manual test, so we can test it live (https://github.com/ckeditor/ckeditor5-basic-styles/tree/master/tests/manual)

It'd be great if you could add these missing things and change the naming of UI items and commands that are mentioned in the review.

And the last thing - do you have permissions to use these icons? Did you create them or found them somewhere?

**Comment by idleb** [comment]
Hello, I updated you mentioned in the review, the feature name,  `contexts.json` and manual test.

About these icons, they was used temporary, I found them from otherwhere. I would need a SVG icon for the default theme.

**Comment by Reinmar** [comment]
We merge the feature in #80. Thank you, @idleb!

**Comment by kylane** [comment]
Thanks guys!

**Pull request closed without merging**
